[package]
name = "metadata"
version = "0.1.0"
authors = ["Joshua M. Clulow <josh@sysmgr.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1", features = [ "derive" ] }
serde_json = "1"
tempfile = "3"
anyhow = "1"
slog = "2.5"
slog-term = "2.5"
atty = "0.2"
#getopts = "0.2"
